[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.2"
humantime = "2.1.0"
lib_rrttp = { path = "../../lib_rrttp" }
log = "0.4.20"
